// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qynfiuutpzmoqloxuhew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5bmZpdXV0cHptb3Fsb3h1aGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzkwMDIsImV4cCI6MjA2NTc1NTAwMn0.SSQdS2HcYdSobjCmLZQuedMsQ2Q7c-Z5Zd2iBdqRKw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);